# 1. Tensor Operations
* This notebook aims to collect codes for tensor operations.


In [1]:
import torch

In [2]:
# Create empty tensor.
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 1.1204e-38],
        [9.6429e-39, 9.2755e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])


In [3]:
# Create Random tensor.
x = torch.rand(5, 3)
print(x)


tensor([[0.4714, 0.0190, 0.1029],
        [0.2139, 0.8910, 0.6987],
        [0.1820, 0.7227, 0.7936],
        [0.4330, 0.1571, 0.0949],
        [0.1449, 0.9528, 0.2462]])


In [4]:
# Create Zeros tensor.
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Create tensor from list.
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
# Use existed tensor.
x = x.new_ones(5, 3, dtype=torch.double)      # new_*
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8526, -0.3021,  0.5249],
        [ 2.2295, -1.3449,  0.2159],
        [-0.7820,  0.7296,  1.0012],
        [ 0.2834, -0.6483, -0.3470],
        [-2.4545,  1.2492,  1.1373]])


In [9]:
# size
print(x.size())

torch.Size([5, 3])


In [10]:
# Add
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

tensor([[ 0.9130,  0.4741,  1.0720],
        [ 3.1208, -0.8371,  0.9533],
        [-0.6085,  1.3754,  1.7437],
        [ 1.2723, -0.0888, -0.1302],
        [-1.9868,  1.8156,  1.3384]])
tensor([[ 0.9130,  0.4741,  1.0720],
        [ 3.1208, -0.8371,  0.9533],
        [-0.6085,  1.3754,  1.7437],
        [ 1.2723, -0.0888, -0.1302],
        [-1.9868,  1.8156,  1.3384]])


In [11]:
# with _
y.add_(x)
print(y)


tensor([[ 0.9130,  0.4741,  1.0720],
        [ 3.1208, -0.8371,  0.9533],
        [-0.6085,  1.3754,  1.7437],
        [ 1.2723, -0.0888, -0.1302],
        [-1.9868,  1.8156,  1.3384]])


In [12]:
# torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 deduced from other dim.
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
# Get value.
x = torch.randn(1)
print(x)
print(x.item())


tensor([0.2676])
0.2676246762275696


In [14]:
# numpy
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [16]:
# CUDA
# is_available Check CUDA available
# ``torch.device`` more tensor to a device
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.2676], device='cuda:0')
tensor([1.2676], dtype=torch.float64)
